apiVersion: v1
kind: Secret
metadata:
  name: g9-secrets
  namespace: service-gestion-incidents
type: Opaque
stringData:
  DB_PASSWORD: ""
  JWT_SECRET: "SGITU_G3_JWT_SECRET_KEY_CHANGE_ME_IN_PRODUCTION_256BITS!!"
