server:
port: 8080

spring:
application:
name: api_gateway

datasource:
url: jdbc:mysql://localhost:3306/gateway_db
username: root
password:
driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
hibernate:
ddl-auto: update
show-sql: true

cloud:
gateway:
routes: []        # Achraf va remplir les routes plus tard

jwt:
secret: G10_SECRET_KEY_SGITU_2025_SUPER_SECURE_KEY_32CHARS
expiration: 3600000
refresh-expiration: 604800000