{
 "title": "SGITU - G10 API Gateway",
 "tags": [
  "SGITU",
  "G10",
  "Gateway"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Gateway UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"g10-api-gateway\"}"
    }
   ]
  },
  {
   "title": "Gateway Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"g10-api-gateway\"}[1m]))",
     "legendFormat": "requests/s"
    }
   ]
  },
  {
   "title": "Gateway Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"g10-api-gateway\",status=~\"4..|5..\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}